name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Vidly
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below so we can reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear, concise description of the bug.
      placeholder: When I navigate to /movies/edit/1, the form shows...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Start the application
        2. Navigate to /movies
        3. Click "Edit" on any movie
        4. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the application is affected?
      options:
        - Controllers (MoviesController, HomeController)
        - Models / ViewModels
        - Views / Razor templates
        - Routing
        - Repository layer
        - Security (headers, CSRF, XSS)
        - Client-side (JS, CSS, Bootstrap)
        - Build / CI
        - Other
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Framework Version
      description: Which .NET Framework version are you running?
      placeholder: "4.5.2"

  - type: input
    id: browser
    attributes:
      label: Browser (if UI-related)
      placeholder: "Chrome 120, Firefox 121, Edge 120"

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Stack Trace
      description: Paste any relevant error output or stack traces.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I can reproduce this bug consistently
