name: ✨ Feature Request
description: Suggest a new feature or improvement for Vidly
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve Vidly? Describe it below. The more context you provide, the better we can evaluate and implement it.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is there a pain point or limitation you've encountered?
      placeholder: Currently there's no way to search movies by title, so users have to scroll through the entire list...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or change you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches? If so, what are their trade-offs?

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the application would this feature touch?
      multiple: true
      options:
        - Controllers
        - Models / ViewModels
        - Views / Razor templates
        - Routing
        - Repository / Data layer
        - Security
        - Client-side (JS, CSS)
        - Build / CI / DevOps
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Estimated Scope
      description: How big do you think this change would be?
      options:
        - Small (single file, < 50 lines)
        - Medium (multiple files, new component)
        - Large (architectural change, new subsystem)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, diagrams, links, or references that help illustrate the feature.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I am willing to submit a PR for this feature
