using System;
using System.Collections.Generic;

namespace Vidly.Models
{
    /// <summary>
    /// Types of anomalies the watchdog can detect.
    /// </summary>
    public enum AnomalyType
    {
        RentalBurst = 1,
        GenreShift = 2,
        ReturnPatternAnomaly = 3,
        InventoryConcentration = 4,
        RateAbuse = 5,
        IdentityRisk = 6
    }

    /// <summary>
    /// Severity classification for anomaly alerts.
    /// </summary>
    public enum AnomalySeverity
    {
        Low = 1,
        Medium = 2,
        High = 3,
        Critical = 4
    }

    /// <summary>
    /// A single anomaly alert generated by the watchdog.
    /// </summary>
    public class AnomalyAlert
    {
        public int Id { get; set; }
        public AnomalyType Type { get; set; }
        public AnomalySeverity Severity { get; set; }
        public int? CustomerId { get; set; }
        public int? MovieId { get; set; }
        public string CustomerName { get; set; }
        public string MovieName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public List<string> Evidence { get; set; } = new List<string>();
        public List<string> RecommendedActions { get; set; } = new List<string>();
        public DateTime DetectedAt { get; set; }
        public bool Acknowledged { get; set; }

        /// <summary>Anomaly score from 0 to 100.</summary>
        public double Score { get; set; }
    }

    /// <summary>
    /// A customer placed on the watchlist due to anomalous behavior.
    /// </summary>
    public class WatchlistEntry
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Reason { get; set; }
        public DateTime AddedAt { get; set; }
        public int AlertCount { get; set; }
        public double RiskScore { get; set; }
        public bool Active { get; set; } = true;
    }

    /// <summary>
    /// Full anomaly scan report.
    /// </summary>
    public class AnomalyReport
    {
        public DateTime GeneratedAt { get; set; }
        public List<AnomalyAlert> Alerts { get; set; } = new List<AnomalyAlert>();
        public List<WatchlistEntry> Watchlist { get; set; } = new List<WatchlistEntry>();

        /// <summary>"Green", "Yellow", "Orange", or "Red".</summary>
        public string ThreatLevel { get; set; }
        public string Summary { get; set; }
        public int TotalAlertsGenerated { get; set; }
        public int CriticalCount { get; set; }
        public int HighCount { get; set; }
        public int MediumCount { get; set; }
        public int LowCount { get; set; }
    }

    /// <summary>
    /// Configurable thresholds for the anomaly watchdog.
    /// </summary>
    public class WatchdogConfig
    {
        /// <summary>Rentals in 24 hours to flag as burst.</summary>
        public int RentalBurstThreshold { get; set; } = 5;

        /// <summary>Days to analyze for genre shift detection.</summary>
        public int GenreShiftWindow { get; set; } = 30;

        /// <summary>Genre distribution distance to trigger alert (0-1).</summary>
        public double GenreShiftThreshold { get; set; } = 0.7;

        /// <summary>Fraction of late returns to flag.</summary>
        public double LateReturnRateThreshold { get; set; } = 0.5;

        /// <summary>Fraction of active rentals held by one customer to flag.</summary>
        public double ConcentrationThreshold { get; set; } = 0.3;

        /// <summary>Maximum watchlist entries.</summary>
        public int MaxWatchlistSize { get; set; } = 50;
    }
}
