using System;
using System.Collections.Generic;

namespace Vidly.Models
{
    /// <summary>
    /// Revenue analytics report covering a specific time period.
    /// </summary>
    public class RevenueReport
    {
        public DateTime PeriodStart { get; set; }
        public DateTime PeriodEnd { get; set; }
        public decimal TotalRevenue { get; set; }
        public decimal RentalRevenue { get; set; }
        public decimal LateFeeRevenue { get; set; }
        public int TotalRentals { get; set; }
        public int CompletedRentals { get; set; }
        public int ActiveRentals { get; set; }
        public int OverdueRentals { get; set; }
        public decimal AverageRevenuePerRental { get; set; }
        public decimal AverageRevenuePerDay { get; set; }
        public List<GenreRevenue> RevenueByGenre { get; set; }
        public List<MembershipRevenue> RevenueByMembership { get; set; }
        public List<MonthlyRevenue> MonthlyTrend { get; set; }
        public List<TopCustomerRevenue> TopCustomers { get; set; }
        public List<TopMovieRevenue> TopMovies { get; set; }
    }

    /// <summary>
    /// Revenue breakdown by movie genre.
    /// </summary>
    public class GenreRevenue
    {
        public Genre Genre { get; set; }
        public decimal Revenue { get; set; }
        public int RentalCount { get; set; }
        public decimal AverageRevenue { get; set; }
        public double SharePercent { get; set; }
    }

    /// <summary>
    /// Revenue breakdown by customer membership tier.
    /// </summary>
    public class MembershipRevenue
    {
        public MembershipType Membership { get; set; }
        public decimal Revenue { get; set; }
        public int CustomerCount { get; set; }
        public int RentalCount { get; set; }
        public decimal AverageRevenuePerCustomer { get; set; }
    }

    /// <summary>
    /// Monthly revenue data point for trend analysis.
    /// </summary>
    public class MonthlyRevenue
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public decimal Revenue { get; set; }
        public int RentalCount { get; set; }
        public decimal GrowthPercent { get; set; }
    }

    /// <summary>
    /// Revenue contribution from a single customer.
    /// </summary>
    public class TopCustomerRevenue
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public decimal TotalRevenue { get; set; }
        public int RentalCount { get; set; }
        public decimal AverageSpend { get; set; }
    }

    /// <summary>
    /// Revenue generated by a single movie.
    /// </summary>
    public class TopMovieRevenue
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public decimal TotalRevenue { get; set; }
        public int RentalCount { get; set; }
        public decimal AverageDailyRate { get; set; }
    }

    /// <summary>
    /// Comparison between two time periods.
    /// </summary>
    public class PeriodComparison
    {
        public RevenueReport Current { get; set; }
        public RevenueReport Previous { get; set; }
        public decimal RevenueChange { get; set; }
        public double RevenueChangePercent { get; set; }
        public int RentalCountChange { get; set; }
        public double RentalCountChangePercent { get; set; }
        public decimal AverageRevenueChange { get; set; }
    }

    /// <summary>
    /// Revenue forecast for a future period.
    /// </summary>
    public class RevenueForecast
    {
        public DateTime ForecastStart { get; set; }
        public DateTime ForecastEnd { get; set; }
        public decimal ProjectedRevenue { get; set; }
        public int ProjectedRentals { get; set; }
        public decimal ConfidenceLow { get; set; }
        public decimal ConfidenceHigh { get; set; }
        public string Method { get; set; }
    }
}
