(* compiler.ml -- Bytecode compiler and stack-based virtual machine
 *
 * Compiles a small expression language to bytecode instructions,
 * then executes them on a stack-based VM. Demonstrates:
 *
 * - Lexer → Parser → Compiler → VM pipeline
 * - Stack-based bytecode execution
 * - Peephole optimization (constant folding, dead store removal)
 * - Variable binding and scoping
 * - Control flow (conditionals, loops, function calls)
 * - Disassembler for inspecting generated bytecode
 *
 * Language features:
 *   let x = expr         -- variable binding
 *   if expr then e1 else e2  -- conditional
 *   while expr do body   -- loop
 *   fun x -> body        -- anonymous function
 *   f x                  -- function application
 *   +, -, *, /, mod      -- arithmetic
 *   =, <>, <, >, <=, >=  -- comparison
 *   and, or, not         -- logical
 *   print expr           -- output
 *)

(* ── Types ──────────────────────────────────────────────────────── *)

type token =
  | TInt of int
  | TBool of bool
  | TIdent of string
  | TPlus | TMinus | TStar | TSlash | TMod
  | TEq | TNeq | TLt | TGt | TLe | TGe
  | TAnd | TOr | TNot
  | TLet | TIn | TIf | TThen | TElse | TWhile | TDo | TDone
  | TFun | TArrow
  | TPrint
  | TLParen | TRParen
  | TSemicolon
  | TEOF

type expr =
  | EInt of int
  | EBool of bool
  | EVar of string
  | EBinop of binop * expr * expr
  | EUnop of unop * expr
  | ELet of string * expr * expr
  | EIf of expr * expr * expr
  | EWhile of expr * expr
  | EFun of string * expr
  | EApp of expr * expr
  | EPrint of expr
  | ESeq of expr * expr

and binop = Add | Sub | Mul | Div | Mod
          | Eq | Neq | Lt | Gt | Le | Ge
          | And | Or

and unop = Neg | Not

type opcode =
  | PUSH_INT of int
  | PUSH_BOOL of bool
  | LOAD of int          (* load from stack offset *)
  | STORE of int         (* store to stack offset *)
  | ADD | SUB | MUL | DIV | MODC
  | EQ | NEQ | LT | GT | LE | GE
  | AND | OR | NOT | NEG
  | JMP of int           (* unconditional jump *)
  | JMP_IF_FALSE of int  (* conditional jump *)
  | CALL of int          (* call function at address *)
  | RET                  (* return from function *)
  | MAKE_CLOSURE of int * int  (* code addr, num captures *)
  | LOAD_CAPTURE of int  (* load from closure captures *)
  | PRINT
  | POP
  | DUP
  | HALT

type value =
  | VInt of int
  | VBool of bool
  | VClosure of int * value array  (* code addr, captures *)
  | VUnit

type program = {
  code : opcode array;
  entry : int;
}

(* ── Lexer ──────────────────────────────────────────────────────── *)

let keywords = [
  "let", TLet; "in", TIn;
  "if", TIf; "then", TThen; "else", TElse;
  "while", TWhile; "do", TDo; "done", TDone;
  "fun", TFun; "true", TBool true; "false", TBool false;
  "and", TAnd; "or", TOr; "not", TNot;
  "mod", TMod; "print", TPrint;
]

let is_alpha c = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c = '_'
let is_digit c = c >= '0' && c <= '9'
let is_alnum c = is_alpha c || is_digit c

let lex input =
  let len = String.length input in
  let pos = ref 0 in
  let tokens = ref [] in
  while !pos < len do
    let c = input.[!pos] in
    if c = ' ' || c = '\t' || c = '\n' || c = '\r' then
      incr pos
    else if is_digit c then begin
      let start = !pos in
      while !pos < len && is_digit input.[!pos] do incr pos done;
      tokens := TInt (int_of_string (String.sub input start (!pos - start))) :: !tokens
    end
    else if is_alpha c then begin
      let start = !pos in
      while !pos < len && is_alnum input.[!pos] do incr pos done;
      let word = String.sub input start (!pos - start) in
      let tok = match List.assoc_opt word keywords with
        | Some t -> t
        | None -> TIdent word
      in
      tokens := tok :: !tokens
    end
    else begin
      (match c with
       | '+' -> tokens := TPlus :: !tokens; incr pos
       | '*' -> tokens := TStar :: !tokens; incr pos
       | '/' -> tokens := TSlash :: !tokens; incr pos
       | '(' -> tokens := TLParen :: !tokens; incr pos
       | ')' -> tokens := TRParen :: !tokens; incr pos
       | ';' -> tokens := TSemicolon :: !tokens; incr pos
       | '-' ->
         incr pos;
         if !pos < len && input.[!pos] = '>' then begin
           tokens := TArrow :: !tokens; incr pos
         end else
           tokens := TMinus :: !tokens
       | '<' ->
         incr pos;
         if !pos < len && input.[!pos] = '=' then begin
           tokens := TLe :: !tokens; incr pos
         end else if !pos < len && input.[!pos] = '>' then begin
           tokens := TNeq :: !tokens; incr pos
         end else
           tokens := TLt :: !tokens
       | '>' ->
         incr pos;
         if !pos < len && input.[!pos] = '=' then begin
           tokens := TGe :: !tokens; incr pos
         end else
           tokens := TGt :: !tokens
       | '=' -> tokens := TEq :: !tokens; incr pos
       | _ -> failwith (Printf.sprintf "Unexpected character '%c' at position %d" c !pos))
    end
  done;
  tokens := TEOF :: !tokens;
  List.rev !tokens

(* ── Parser (recursive descent) ─────────────────────────────────── *)

type parser_state = {
  mutable toks : token list;
}

let make_parser tokens = { toks = tokens }

let peek ps = match ps.toks with t :: _ -> t | [] -> TEOF

let advance ps =
  match ps.toks with
  | _ :: rest -> ps.toks <- rest
  | [] -> ()

let expect ps tok =
  if peek ps = tok then advance ps
  else failwith (Printf.sprintf "Expected token, got something else")

let rec parse_expr ps = parse_seq ps

and parse_seq ps =
  let e = parse_let ps in
  if peek ps = TSemicolon then begin
    advance ps;
    let e2 = parse_seq ps in
    ESeq (e, e2)
  end else e

and parse_let ps =
  match peek ps with
  | TLet ->
    advance ps;
    let name = match peek ps with
      | TIdent s -> advance ps; s
      | _ -> failwith "Expected identifier after 'let'"
    in
    expect ps TEq;
    let value = parse_let ps in
    expect ps TIn;
    let body = parse_seq ps in
    ELet (name, value, body)
  | TIf -> parse_if ps
  | TWhile -> parse_while ps
  | TFun -> parse_fun ps
  | TPrint -> parse_print ps
  | _ -> parse_or ps

and parse_if ps =
  advance ps;
  let cond = parse_or ps in
  expect ps TThen;
  let then_e = parse_seq ps in
  expect ps TElse;
  let else_e = parse_seq ps in
  EIf (cond, then_e, else_e)

and parse_while ps =
  advance ps;
  let cond = parse_or ps in
  expect ps TDo;
  let body = parse_seq ps in
  expect ps TDone;
  EWhile (cond, body)

and parse_fun ps =
  advance ps;
  let param = match peek ps with
    | TIdent s -> advance ps; s
    | _ -> failwith "Expected parameter name"
  in
  expect ps TArrow;
  let body = parse_seq ps in
  EFun (param, body)

and parse_print ps =
  advance ps;
  let e = parse_or ps in
  EPrint e

and parse_or ps =
  let e = ref (parse_and ps) in
  while peek ps = TOr do
    advance ps;
    e := EBinop (Or, !e, parse_and ps)
  done;
  !e

and parse_and ps =
  let e = ref (parse_cmp ps) in
  while peek ps = TAnd do
    advance ps;
    e := EBinop (And, !e, parse_cmp ps)
  done;
  !e

and parse_cmp ps =
  let e = parse_add ps in
  match peek ps with
  | TEq -> advance ps; EBinop (Eq, e, parse_add ps)
  | TNeq -> advance ps; EBinop (Neq, e, parse_add ps)
  | TLt -> advance ps; EBinop (Lt, e, parse_add ps)
  | TGt -> advance ps; EBinop (Gt, e, parse_add ps)
  | TLe -> advance ps; EBinop (Le, e, parse_add ps)
  | TGe -> advance ps; EBinop (Ge, e, parse_add ps)
  | _ -> e

and parse_add ps =
  let e = ref (parse_mul ps) in
  while peek ps = TPlus || peek ps = TMinus do
    let op = if peek ps = TPlus then Add else Sub in
    advance ps;
    e := EBinop (op, !e, parse_mul ps)
  done;
  !e

and parse_mul ps =
  let e = ref (parse_unary ps) in
  while peek ps = TStar || peek ps = TSlash || peek ps = TMod do
    let op = match peek ps with
      | TStar -> Mul | TSlash -> Div | _ -> Mod
    in
    advance ps;
    e := EBinop (op, !e, parse_unary ps)
  done;
  !e

and parse_unary ps =
  match peek ps with
  | TMinus -> advance ps; EUnop (Neg, parse_unary ps)
  | TNot -> advance ps; EUnop (Not, parse_unary ps)
  | _ -> parse_app ps

and parse_app ps =
  let f = parse_atom ps in
  match peek ps with
  | TInt _ | TBool _ | TIdent _ | TLParen ->
    let arg = parse_atom ps in
    EApp (f, arg)
  | _ -> f

and parse_atom ps =
  match peek ps with
  | TInt n -> advance ps; EInt n
  | TBool b -> advance ps; EBool b
  | TIdent s -> advance ps; EVar s
  | TLParen ->
    advance ps;
    let e = parse_seq ps in
    expect ps TRParen;
    e
  | _ -> failwith "Unexpected token in expression"

let parse tokens =
  let ps = make_parser tokens in
  let e = parse_expr ps in
  if peek ps <> TEOF then failwith "Unexpected tokens after expression";
  e

(* ── Compiler ───────────────────────────────────────────────────── *)

type compile_env = {
  locals : (string * int) list;  (* name -> stack offset *)
  depth : int;                   (* current stack depth *)
  captures : string list;        (* captured variables for closures *)
}

let empty_env = { locals = []; depth = 0; captures = [] }

let lookup_var env name =
  match List.assoc_opt name env.locals with
  | Some offset -> `Local offset
  | None ->
    let rec find_capture i = function
      | [] -> failwith (Printf.sprintf "Unbound variable: %s" name)
      | c :: _ when c = name -> `Capture i
      | _ :: rest -> find_capture (i + 1) rest
    in
    find_capture 0 env.captures

type compilation = {
  mutable instrs : opcode list;
  mutable func_blocks : opcode list list;  (* compiled functions *)
}

let new_compilation () = { instrs = []; func_blocks = [] }

let emit comp op = comp.instrs <- op :: comp.instrs

let current_addr comp = List.length comp.instrs

let patch_jmp instrs addr target =
  let arr = Array.of_list (List.rev instrs) in
  (match arr.(addr) with
   | JMP _ -> arr.(addr) <- JMP target
   | JMP_IF_FALSE _ -> arr.(addr) <- JMP_IF_FALSE target
   | _ -> failwith "Cannot patch non-jump instruction");
  Array.to_list (Array.to_list arr |> List.rev |> fun _ -> arr |> Array.to_list)

(* Free variables in an expression *)
let rec free_vars bound = function
  | EInt _ | EBool _ -> []
  | EVar x -> if List.mem x bound then [] else [x]
  | EBinop (_, a, b) -> free_vars bound a @ free_vars bound b
  | EUnop (_, a) -> free_vars bound a
  | ELet (x, v, body) -> free_vars bound v @ free_vars (x :: bound) body
  | EIf (c, t, e) -> free_vars bound c @ free_vars bound t @ free_vars bound e
  | EWhile (c, body) -> free_vars bound c @ free_vars bound body
  | EFun (x, body) -> free_vars (x :: bound) body
  | EApp (f, arg) -> free_vars bound f @ free_vars bound arg
  | EPrint e -> free_vars bound e
  | ESeq (a, b) -> free_vars bound a @ free_vars bound b

let unique_list lst =
  List.fold_left (fun acc x -> if List.mem x acc then acc else x :: acc) [] lst
  |> List.rev

let rec compile_expr comp env = function
  | EInt n ->
    emit comp (PUSH_INT n)
  | EBool b ->
    emit comp (PUSH_BOOL b)
  | EVar name ->
    (match lookup_var env name with
     | `Local offset -> emit comp (LOAD (env.depth - offset - 1))
     | `Capture i -> emit comp (LOAD_CAPTURE i))
  | EBinop (op, a, b) ->
    compile_expr comp env a;
    compile_expr comp { env with depth = env.depth + 1 } b;
    let instr = match op with
      | Add -> ADD | Sub -> SUB | Mul -> MUL | Div -> DIV | Mod -> MODC
      | Eq -> EQ | Neq -> NEQ | Lt -> LT | Gt -> GT | Le -> LE | Ge -> GE
      | And -> AND | Or -> OR
    in
    emit comp instr
  | EUnop (op, a) ->
    compile_expr comp env a;
    emit comp (match op with Neg -> NEG | Not -> NOT)
  | ELet (name, value, body) ->
    compile_expr comp env value;
    let env' = { env with
      locals = (name, env.depth) :: env.locals;
      depth = env.depth + 1;
    } in
    compile_expr comp env' body;
    (* swap result over the let binding, then pop binding *)
    emit comp (STORE (0));  (* result is on top, store temp *)
    emit comp POP;
    emit comp (LOAD 0)  (* this is a simplified approach *)
  | EIf (cond, then_e, else_e) ->
    compile_expr comp env cond;
    let false_jmp = current_addr comp in
    emit comp (JMP_IF_FALSE 0);  (* placeholder *)
    compile_expr comp env then_e;
    let end_jmp = current_addr comp in
    emit comp (JMP 0);  (* placeholder *)
    let else_addr = current_addr comp in
    compile_expr comp env else_e;
    let end_addr = current_addr comp in
    (* Patch jumps *)
    let arr = Array.of_list (List.rev comp.instrs) in
    arr.(false_jmp) <- JMP_IF_FALSE else_addr;
    arr.(end_jmp) <- JMP end_addr;
    comp.instrs <- List.rev (Array.to_list arr)
  | EWhile (cond, body) ->
    let loop_start = current_addr comp in
    compile_expr comp env cond;
    let exit_jmp = current_addr comp in
    emit comp (JMP_IF_FALSE 0);  (* placeholder *)
    compile_expr comp env body;
    emit comp POP;  (* discard body result *)
    emit comp (JMP loop_start);
    let end_addr = current_addr comp in
    let arr = Array.of_list (List.rev comp.instrs) in
    arr.(exit_jmp) <- JMP_IF_FALSE end_addr;
    comp.instrs <- List.rev (Array.to_list arr);
    emit comp (PUSH_BOOL false)  (* while returns unit-like *)
  | EFun (param, body) ->
    let bound = List.map fst env.locals @ env.captures in
    let fv = unique_list (free_vars (param :: bound) body) in
    (* push captured values *)
    List.iter (fun v ->
      (match lookup_var env v with
       | `Local offset -> emit comp (LOAD (env.depth - offset - 1))
       | `Capture i -> emit comp (LOAD_CAPTURE i))
    ) fv;
    (* Compile function body into a separate block *)
    let saved = comp.instrs in
    comp.instrs <- [];
    let func_env = {
      locals = [(param, 0)];
      depth = 1;
      captures = fv;
    } in
    compile_expr comp func_env body;
    emit comp RET;
    let func_code = List.rev comp.instrs in
    comp.instrs <- saved;
    let func_id = List.length comp.func_blocks in
    comp.func_blocks <- comp.func_blocks @ [func_code];
    emit comp (MAKE_CLOSURE (func_id, List.length fv))
  | EApp (f, arg) ->
    compile_expr comp env arg;
    compile_expr comp { env with depth = env.depth + 1 } f;
    emit comp (CALL 0)  (* CALL uses closure on top of stack *)
  | EPrint e ->
    compile_expr comp env e;
    emit comp DUP;
    emit comp PRINT
  | ESeq (a, b) ->
    compile_expr comp env a;
    emit comp POP;
    compile_expr comp env b

let compile expr =
  let comp = new_compilation () in
  compile_expr comp empty_env expr;
  emit comp HALT;
  let main_code = List.rev comp.instrs in
  (* Layout: func blocks first, then main *)
  let func_offsets = ref [] in
  let all_code = ref [] in
  let offset = ref 0 in
  List.iter (fun block ->
    func_offsets := !offset :: !func_offsets;
    all_code := !all_code @ block;
    offset := !offset + List.length block
  ) comp.func_blocks;
  let func_offsets = List.rev !func_offsets in
  let entry = !offset in
  all_code := !all_code @ main_code;
  (* Fix MAKE_CLOSURE addresses *)
  let code = Array.of_list !all_code in
  Array.iteri (fun _i op ->
    match op with
    | MAKE_CLOSURE (func_id, n) ->
      let addr = List.nth func_offsets func_id in
      code.(_i) <- MAKE_CLOSURE (addr, n)
    | _ -> ()
  ) code;
  (* Fix JMP/JMP_IF_FALSE in main code to be relative to entry *)
  for i = entry to Array.length code - 1 do
    match code.(i) with
    | JMP a -> code.(i) <- JMP (a + entry)
    | JMP_IF_FALSE a -> code.(i) <- JMP_IF_FALSE (a + entry)
    | _ -> ()
  done;
  { code; entry }

(* ── Peephole Optimizer ─────────────────────────────────────────── *)

let optimize prog =
  let code = Array.copy prog.code in
  let changed = ref true in
  while !changed do
    changed := false;
    for i = 0 to Array.length code - 2 do
      match code.(i), code.(i + 1) with
      (* Constant folding: PUSH a; PUSH b; ADD -> PUSH (a+b) *)
      | PUSH_INT a, _ when i + 2 < Array.length code ->
        (match code.(i + 1), code.(i + 2) with
         | PUSH_INT b, ADD ->
           code.(i) <- PUSH_INT (a + b);
           code.(i + 1) <- DUP; code.(i + 2) <- POP;  (* NOP equivalent *)
           changed := true
         | PUSH_INT b, SUB ->
           code.(i) <- PUSH_INT (a - b);
           code.(i + 1) <- DUP; code.(i + 2) <- POP;
           changed := true
         | PUSH_INT b, MUL ->
           code.(i) <- PUSH_INT (a * b);
           code.(i + 1) <- DUP; code.(i + 2) <- POP;
           changed := true
         | _ -> ())
      (* Identity operations: x + 0 = x, x * 1 = x *)
      | PUSH_INT 0, ADD ->
        code.(i) <- DUP; code.(i + 1) <- POP;
        changed := true
      | PUSH_INT 1, MUL ->
        code.(i) <- DUP; code.(i + 1) <- POP;
        changed := true
      (* Double negation *)
      | NEG, NEG ->
        code.(i) <- DUP; code.(i + 1) <- POP;
        changed := true
      | NOT, NOT ->
        code.(i) <- DUP; code.(i + 1) <- POP;
        changed := true
      (* Push then pop *)
      | PUSH_INT _, POP ->
        code.(i) <- DUP; code.(i + 1) <- POP;
        changed := true
      | PUSH_BOOL _, POP ->
        code.(i) <- DUP; code.(i + 1) <- POP;
        changed := true
      | _ -> ()
    done
  done;
  (* Remove DUP; POP sequences (NOPs from above) *)
  let filtered = Array.to_list code
    |> List.filteri (fun i op ->
      match op with
      | DUP when i + 1 < Array.length code && code.(i + 1) = POP -> false
      | POP when i > 0 && code.(i - 1) = DUP ->
        (* Check if the DUP at i-1 is also being removed *)
        (match code.(i - 1) with DUP -> false | _ -> true)
      | _ -> true)
  in
  (* Rebuild with corrected jump targets *)
  (* For simplicity, we keep the NOP approach and just use the filtered code *)
  { code = Array.of_list filtered; entry = prog.entry }

(* ── Virtual Machine ────────────────────────────────────────────── *)

type vm = {
  mutable stack : value array;
  mutable sp : int;       (* stack pointer *)
  mutable pc : int;       (* program counter *)
  mutable frames : frame list;
  mutable output : string list;  (* captured print output *)
}

and frame = {
  return_addr : int;
  base_sp : int;
  captures : value array;
}

let make_vm size = {
  stack = Array.make size VUnit;
  sp = 0;
  pc = 0;
  frames = [];
  output = [];
}

let push vm v =
  if vm.sp >= Array.length vm.stack then
    failwith "Stack overflow";
  vm.stack.(vm.sp) <- v;
  vm.sp <- vm.sp + 1

let pop vm =
  if vm.sp <= 0 then failwith "Stack underflow";
  vm.sp <- vm.sp - 1;
  vm.stack.(vm.sp)

let peek_stack vm =
  if vm.sp <= 0 then failwith "Stack underflow";
  vm.stack.(vm.sp - 1)

let string_of_value = function
  | VInt n -> string_of_int n
  | VBool b -> string_of_bool b
  | VClosure (addr, _) -> Printf.sprintf "<closure@%d>" addr
  | VUnit -> "()"

let int_of_value = function
  | VInt n -> n
  | v -> failwith (Printf.sprintf "Expected int, got %s" (string_of_value v))

let bool_of_value = function
  | VBool b -> b
  | VInt 0 -> false
  | VInt _ -> true
  | v -> failwith (Printf.sprintf "Expected bool, got %s" (string_of_value v))

let run_vm prog max_steps =
  let vm = make_vm 1024 in
  vm.pc <- prog.entry;
  let steps = ref 0 in
  let running = ref true in
  while !running && !steps < max_steps do
    incr steps;
    if vm.pc >= Array.length prog.code then begin
      running := false
    end else begin
      let op = prog.code.(vm.pc) in
      vm.pc <- vm.pc + 1;
      match op with
      | PUSH_INT n -> push vm (VInt n)
      | PUSH_BOOL b -> push vm (VBool b)
      | LOAD offset ->
        let idx = vm.sp - offset - 1 in
        if idx < 0 || idx >= vm.sp then
          failwith (Printf.sprintf "LOAD: invalid offset %d (sp=%d)" offset vm.sp);
        push vm vm.stack.(idx)
      | STORE offset ->
        let v = pop vm in
        let idx = vm.sp - offset - 1 in
        vm.stack.(idx) <- v
      | LOAD_CAPTURE i ->
        (match vm.frames with
         | frame :: _ ->
           if i >= Array.length frame.captures then
             failwith "LOAD_CAPTURE: index out of bounds";
           push vm frame.captures.(i)
         | [] -> failwith "LOAD_CAPTURE: no active frame")
      | ADD ->
        let b = int_of_value (pop vm) in
        let a = int_of_value (pop vm) in
        push vm (VInt (a + b))
      | SUB ->
        let b = int_of_value (pop vm) in
        let a = int_of_value (pop vm) in
        push vm (VInt (a - b))
      | MUL ->
        let b = int_of_value (pop vm) in
        let a = int_of_value (pop vm) in
        push vm (VInt (a * b))
      | DIV ->
        let b = int_of_value (pop vm) in
        if b = 0 then failwith "Division by zero";
        let a = int_of_value (pop vm) in
        push vm (VInt (a / b))
      | MODC ->
        let b = int_of_value (pop vm) in
        if b = 0 then failwith "Modulo by zero";
        let a = int_of_value (pop vm) in
        push vm (VInt (a mod b))
      | EQ ->
        let b = pop vm in
        let a = pop vm in
        push vm (VBool (a = b))
      | NEQ ->
        let b = pop vm in
        let a = pop vm in
        push vm (VBool (a <> b))
      | LT ->
        let b = int_of_value (pop vm) in
        let a = int_of_value (pop vm) in
        push vm (VBool (a < b))
      | GT ->
        let b = int_of_value (pop vm) in
        let a = int_of_value (pop vm) in
        push vm (VBool (a > b))
      | LE ->
        let b = int_of_value (pop vm) in
        let a = int_of_value (pop vm) in
        push vm (VBool (a <= b))
      | GE ->
        let b = int_of_value (pop vm) in
        let a = int_of_value (pop vm) in
        push vm (VBool (a >= b))
      | AND ->
        let b = bool_of_value (pop vm) in
        let a = bool_of_value (pop vm) in
        push vm (VBool (a && b))
      | OR ->
        let b = bool_of_value (pop vm) in
        let a = bool_of_value (pop vm) in
        push vm (VBool (a || b))
      | NOT ->
        let a = bool_of_value (pop vm) in
        push vm (VBool (not a))
      | NEG ->
        let a = int_of_value (pop vm) in
        push vm (VInt (-a))
      | JMP addr ->
        vm.pc <- addr
      | JMP_IF_FALSE addr ->
        let cond = bool_of_value (pop vm) in
        if not cond then vm.pc <- addr
      | CALL _ ->
        let closure = pop vm in
        (match closure with
         | VClosure (addr, captures) ->
           let frame = {
             return_addr = vm.pc;
             base_sp = vm.sp;
             captures;
           } in
           vm.frames <- frame :: vm.frames;
           vm.pc <- addr
         | _ -> failwith "Cannot call non-closure value")
      | RET ->
        let result = pop vm in
        (match vm.frames with
         | frame :: rest ->
           vm.sp <- frame.base_sp;
           vm.pc <- frame.return_addr;
           vm.frames <- rest;
           push vm result
         | [] -> failwith "RET: no frame to return to")
      | MAKE_CLOSURE (addr, n) ->
        let captures = Array.init n (fun _ -> pop vm) in
        (* Reverse because we popped in reverse order *)
        let captures = Array.init n (fun i -> captures.(n - 1 - i)) in
        push vm (VClosure (addr, captures))
      | PRINT ->
        let v = peek_stack vm in
        let s = string_of_value v in
        vm.output <- s :: vm.output;
        Printf.printf "%s\n" s
      | POP -> ignore (pop vm)
      | DUP ->
        let v = peek_stack vm in
        push vm v
      | HALT -> running := false
    end
  done;
  if !steps >= max_steps then
    failwith (Printf.sprintf "Execution exceeded %d steps (infinite loop?)" max_steps);
  let result = if vm.sp > 0 then pop vm else VUnit in
  (result, List.rev vm.output, !steps)

(* ── Disassembler ───────────────────────────────────────────────── *)

let string_of_opcode = function
  | PUSH_INT n -> Printf.sprintf "PUSH_INT %d" n
  | PUSH_BOOL b -> Printf.sprintf "PUSH_BOOL %b" b
  | LOAD n -> Printf.sprintf "LOAD %d" n
  | STORE n -> Printf.sprintf "STORE %d" n
  | LOAD_CAPTURE n -> Printf.sprintf "LOAD_CAPTURE %d" n
  | ADD -> "ADD" | SUB -> "SUB" | MUL -> "MUL" | DIV -> "DIV" | MODC -> "MOD"
  | EQ -> "EQ" | NEQ -> "NEQ" | LT -> "LT" | GT -> "GT" | LE -> "LE" | GE -> "GE"
  | AND -> "AND" | OR -> "OR" | NOT -> "NOT" | NEG -> "NEG"
  | JMP n -> Printf.sprintf "JMP %d" n
  | JMP_IF_FALSE n -> Printf.sprintf "JMP_IF_FALSE %d" n
  | CALL n -> Printf.sprintf "CALL %d" n
  | RET -> "RET"
  | MAKE_CLOSURE (a, n) -> Printf.sprintf "MAKE_CLOSURE addr=%d captures=%d" a n
  | PRINT -> "PRINT" | POP -> "POP" | DUP -> "DUP" | HALT -> "HALT"

let disassemble prog =
  Printf.printf "=== Bytecode (entry=%d, %d instructions) ===\n"
    prog.entry (Array.length prog.code);
  Array.iteri (fun i op ->
    let marker = if i = prog.entry then " <entry>" else "" in
    Printf.printf "  %04d: %-35s%s\n" i (string_of_opcode op) marker
  ) prog.code;
  Printf.printf "=== End ===\n"

(* ── High-level API ─────────────────────────────────────────────── *)

let compile_and_run ?(max_steps=100000) ?(show_bytecode=false) source =
  let tokens = lex source in
  let ast = parse tokens in
  let prog = compile ast in
  if show_bytecode then disassemble prog;
  run_vm prog max_steps

let compile_and_run_optimized ?(max_steps=100000) ?(show_bytecode=false) source =
  let tokens = lex source in
  let ast = parse tokens in
  let prog = optimize (compile ast) in
  if show_bytecode then disassemble prog;
  run_vm prog max_steps

(* ── Pretty printer for AST ─────────────────────────────────────── *)

let rec string_of_expr = function
  | EInt n -> string_of_int n
  | EBool b -> string_of_bool b
  | EVar s -> s
  | EBinop (op, a, b) ->
    Printf.sprintf "(%s %s %s)" (string_of_expr a) (string_of_binop op) (string_of_expr b)
  | EUnop (Neg, a) -> Printf.sprintf "(-%s)" (string_of_expr a)
  | EUnop (Not, a) -> Printf.sprintf "(not %s)" (string_of_expr a)
  | ELet (x, v, body) ->
    Printf.sprintf "(let %s = %s in %s)" x (string_of_expr v) (string_of_expr body)
  | EIf (c, t, e) ->
    Printf.sprintf "(if %s then %s else %s)" (string_of_expr c) (string_of_expr t) (string_of_expr e)
  | EWhile (c, body) ->
    Printf.sprintf "(while %s do %s done)" (string_of_expr c) (string_of_expr body)
  | EFun (x, body) -> Printf.sprintf "(fun %s -> %s)" x (string_of_expr body)
  | EApp (f, arg) -> Printf.sprintf "(%s %s)" (string_of_expr f) (string_of_expr arg)
  | EPrint e -> Printf.sprintf "(print %s)" (string_of_expr e)
  | ESeq (a, b) -> Printf.sprintf "%s; %s" (string_of_expr a) (string_of_expr b)

and string_of_binop = function
  | Add -> "+" | Sub -> "-" | Mul -> "*" | Div -> "/" | Mod -> "mod"
  | Eq -> "=" | Neq -> "<>" | Lt -> "<" | Gt -> ">" | Le -> "<=" | Ge -> ">="
  | And -> "and" | Or -> "or"

(* ── Tests ──────────────────────────────────────────────────────── *)

let test_count = ref 0
let pass_count = ref 0
let fail_count = ref 0

let assert_equal name expected actual =
  incr test_count;
  if expected = actual then begin
    incr pass_count
  end else begin
    incr fail_count;
    Printf.printf "FAIL: %s\n  expected: %s\n  actual:   %s\n" name expected actual
  end

let assert_result name expected_val source =
  let (result, _, _) = compile_and_run source in
  assert_equal name (string_of_value expected_val) (string_of_value result)

let assert_output name expected_output source =
  let (_, output, _) = compile_and_run source in
  assert_equal name (String.concat "," expected_output) (String.concat "," output)

let assert_optimized name expected_val source =
  let (result, _, _) = compile_and_run_optimized source in
  assert_equal name (string_of_value expected_val) (string_of_value result)

let assert_fails name source =
  incr test_count;
  try
    ignore (compile_and_run source);
    incr fail_count;
    Printf.printf "FAIL: %s (expected failure, but succeeded)\n" name
  with _ ->
    incr pass_count

let () =
  Printf.printf "\n=== Compiler & VM Tests ===\n\n";

  (* ── Lexer tests ── *)
  let tokens = lex "42 + x" in
  assert_equal "lex integers and idents" "3"
    (string_of_int (List.length tokens - 1));  (* -1 for EOF *)

  let tokens = lex "let x = 10 in x + 1" in
  assert_equal "lex keywords" "8"
    (string_of_int (List.length tokens - 1));

  let tokens = lex "if true then 1 else 0" in
  assert_equal "lex if-then-else" "6"
    (string_of_int (List.length tokens - 1));

  let tokens = lex "<= >= <> ->" in
  assert_equal "lex multi-char operators" "4"
    (string_of_int (List.length tokens - 1));

  (* ── Parser tests ── *)
  let ast = parse (lex "1 + 2 * 3") in
  assert_equal "parse precedence" "(1 + (2 * 3))" (string_of_expr ast);

  let ast = parse (lex "1 * 2 + 3") in
  assert_equal "parse left assoc" "((1 * 2) + 3)" (string_of_expr ast);

  let ast = parse (lex "not true and false") in
  assert_equal "parse unary precedence" "((not true) and false)" (string_of_expr ast);

  let ast = parse (lex "let x = 5 in x + 1") in
  assert_equal "parse let" "(let x = 5 in (x + 1))" (string_of_expr ast);

  (* ── Arithmetic tests ── *)
  assert_result "int literal" (VInt 42) "42";
  assert_result "addition" (VInt 7) "3 + 4";
  assert_result "subtraction" (VInt 5) "10 - 5";
  assert_result "multiplication" (VInt 24) "6 * 4";
  assert_result "division" (VInt 5) "15 / 3";
  assert_result "modulo" (VInt 1) "7 mod 3";
  assert_result "complex expr" (VInt 14) "2 + 3 * 4";
  assert_result "parenthesized" (VInt 20) "(2 + 3) * 4";
  assert_result "negation" (VInt (-5)) "-5";
  assert_result "double neg" (VInt 5) "- -5";
  assert_result "nested arith" (VInt 10) "(1 + 2) * 3 + 1";

  (* ── Boolean tests ── *)
  assert_result "true" (VBool true) "true";
  assert_result "false" (VBool false) "false";
  assert_result "not true" (VBool false) "not true";
  assert_result "not false" (VBool true) "not false";
  assert_result "and tt" (VBool true) "true and true";
  assert_result "and tf" (VBool false) "true and false";
  assert_result "or ff" (VBool false) "false or false";
  assert_result "or tf" (VBool true) "true or false";

  (* ── Comparison tests ── *)
  assert_result "eq true" (VBool true) "5 = 5";
  assert_result "eq false" (VBool false) "5 = 6";
  assert_result "neq" (VBool true) "5 <> 6";
  assert_result "lt" (VBool true) "3 < 5";
  assert_result "gt" (VBool true) "5 > 3";
  assert_result "le eq" (VBool true) "5 <= 5";
  assert_result "le lt" (VBool true) "3 <= 5";
  assert_result "ge" (VBool true) "5 >= 5";

  (* ── Variable binding tests ── *)
  assert_result "let simple" (VInt 10) "let x = 10 in x";
  assert_result "let with expr" (VInt 15) "let x = 10 in x + 5";
  assert_result "nested let" (VInt 30)
    "let x = 10 in let y = 20 in x + y";
  assert_result "let shadow" (VInt 5)
    "let x = 10 in let x = 5 in x";
  assert_result "let scope" (VInt 25)
    "let x = 5 in let y = x * 5 in y";

  (* ── Conditional tests ── *)
  assert_result "if true" (VInt 1) "if true then 1 else 0";
  assert_result "if false" (VInt 0) "if false then 1 else 0";
  assert_result "if cmp" (VInt 10)
    "if 5 > 3 then 10 else 20";
  assert_result "nested if" (VInt 2)
    "if false then 1 else if true then 2 else 3";
  assert_result "if with let" (VInt 100)
    "let x = 10 in if x > 5 then x * 10 else x";

  (* ── Print tests ── *)
  assert_output "print int" ["42"] "print 42";
  assert_output "print bool" ["true"] "print true";
  assert_output "print expr" ["15"] "print (3 * 5)";

  (* ── Sequence tests ── *)
  assert_result "seq returns last" (VInt 20) "10; 20";
  assert_output "seq both print" ["10"; "20"] "print 10; print 20";

  (* ── Function tests ── *)
  assert_result "identity fn" (VInt 5)
    "let f = fun x -> x in f 5";
  assert_result "add fn" (VInt 8)
    "let double = fun x -> x + x in double 4";
  assert_result "fn with closure" (VInt 15)
    "let a = 10 in let add_a = fun x -> x + a in add_a 5";
  assert_result "nested fn" (VInt 30)
    "let mul = fun x -> x * 10 in let add = fun x -> x + 1 in mul (add 2)";

  (* ── While loop tests ── *)
  assert_output "while countdown" ["3"; "2"; "1"]
    "let x = 3 in while x > 0 do print x; let x = x - 1 in x done";

  (* ── Error handling tests ── *)
  assert_fails "div by zero" "1 / 0";
  assert_fails "mod by zero" "1 mod 0";
  assert_fails "unbound var" "x + 1";

  (* ── Optimizer tests ── *)
  assert_optimized "const fold add" (VInt 10) "3 + 7";
  assert_optimized "const fold mul" (VInt 12) "3 * 4";
  assert_optimized "const fold sub" (VInt 5) "8 - 3";
  assert_optimized "opt complex" (VInt 30) "let x = 5 in x * (2 + 4)";
  assert_optimized "double neg opt" (VInt 5) "- - 5";
  assert_optimized "identity add" (VInt 5) "5 + 0";
  assert_optimized "identity mul" (VInt 5) "5 * 1";

  (* ── Disassembler smoke test ── *)
  let tokens = lex "1 + 2" in
  let ast = parse tokens in
  let prog = compile ast in
  assert_equal "disasm entry set" "true"
    (string_of_bool (prog.entry >= 0));
  assert_equal "disasm has code" "true"
    (string_of_bool (Array.length prog.code > 0));

  (* ── Integration tests ── *)
  assert_result "factorial-like" (VInt 120)
    "let f = fun n -> if n <= 1 then 1 else n * (f (n - 1)) in f 5";

  assert_output "fizzbuzz-like" ["1"; "2"; "0"; "4"; "5"]
    "print 1; print 2; print (6 mod 3); print 4; print 5";

  (* ── Summary ── *)
  Printf.printf "\n%d/%d tests passed" !pass_count !test_count;
  if !fail_count > 0 then
    Printf.printf " (%d FAILED)" !fail_count;
  Printf.printf "\n";

  (* Demo *)
  Printf.printf "\n=== Demo: Compile and Disassemble ===\n";
  ignore (compile_and_run ~show_bytecode:true
    "let x = 10 in let y = 20 in x + y");

  Printf.printf "\n=== Demo: Optimized vs Unoptimized ===\n";
  let source = "2 + 3 * 4 + 1" in
  let prog_unopt = compile (parse (lex source)) in
  let prog_opt = optimize prog_unopt in
  Printf.printf "Unoptimized: %d instructions\n" (Array.length prog_unopt.code);
  Printf.printf "Optimized:   %d instructions\n" (Array.length prog_opt.code);

  Printf.printf "\n=== Demo: Function with Closure ===\n";
  ignore (compile_and_run ~show_bytecode:true
    "let base = 100 in let add_base = fun x -> x + base in add_base 42")
