name: Release Drafter

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-release-draft:
    name: Draft next release
    runs-on: ubuntu-latest
    steps:
      - name: Run release drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
